= Core belief

A core belief is a central part of cultivation. It describes the motivation behind cultivation and what you believe in. While acting according to your core belief you can nurture it and have it grow.

Skills that align with your core belief are more efficient than others. You can use the power of your core belief to increase the effect of skills which are in tune with it.


Your current core belief 'For the family' is a common one, that focuses on the family. There are generally three routes most people take, with many others available as well.

Route one: +
The happiness of the family. Here the happiness of the family and its members stand in the foreground. It mostly focuses on supporting skills, that can help family members attain happiness.

Route two: +
The glory of the family. This route focuses on the glory of the family. An important point to watch is what glory means, but generally, it can be described as the reputation the family has in the eyes of the others. This route focuses mainly on combat skills since a good way to increase the reputation of the family is to fight against strong monsters or cultivators.

Route three: +
I'm the family and the family is me. This route is an egocentric one, where the focus is on oneself and the family is seen as an extension of oneself. Everything you and the family do is for you to enjoy.

Recommend route: +
A mixture between route one and two is recommended since it can balance the two. Sometimes a little bit of route three is advisable as well since it can reduce the risk of being used by the family.

... 
