= All the quests in the story
:toc:

== Curently active quests (ch. 153)

=== Limitless Domination (SS)

You have been dominated by Lady Meilo, which has lead to your bloodline burning up in defense, awakening your innate 'Dominate' talent. But the situation it has happened has left a mark. As long as you aren't capable of overcoming this, you won't be able to elevate your `Dominate` to the highest grade. Instead, it will be capped at the level of Lady Meilo.

Your `Dominate` talent is currently capped at rank S and level 50.

Task: +
To get rid of the shame of being dominated it is necessary for you to get your revenge. Thus it is required for you to make Lady Meilo your pet and have her wear the corresponding collar. 


=== Practiced domination

Just like everything else dominating someone requires practice. But just going around and using it indiscriminately won't make for good practice. Instead, it is a good strategy to orient oneself at the situation one was in when the talent has awoken. 

You have awoken your talent while being slightly dominated by a humanoid female, thus dominating humanoid female's is the best choice for you. Use the given collars to mark your domain.

Task: +
Use `Dominate` to make five female humanoids wear the `Collar of Submission`.
You have currently made 0/5 wear the collar.

You have 5/5 `Collar of Submission` available. You can get them in your inventory in the quest section.


=== First steps to real Pill Refining

Started: Chapter 126

Task:  + 
Learn Bea Klein's pill refining technique and use it to refine a 'Smaller Strength Pill' of at least normal quality.

Rewards:

- Low-grade Herb Ring, capable of only storing herbs.
- A slight increase in soul strength. 
- A aandom low-grade herb.

Time limit: +
Unlimited

=== Traversing the grassland (F) (Nightmare Mode) (1)
(Training dungeon quest)

You have entered the Grand Endless Grasslands, which is filled with danger and opportunities. Your goal is to reach the grand tree, which is the only tree growing on this grassland. All the while fighting against the native monsters of the grassland.

Tasks (Part 1):
- Follow the arrow in the Direction Cube until you reach the grass hut.

Bonus tasks:

- Slay 50 Grass Wolfes
- Slay 10 Grass Vultures
- Slay 5 Gigant Grass Pythons

Rewards:

- Access to floor 6
- 1 Silver
- A random item box (req. Nightmare Mode)

Bonus Rewards:

For each bonus task you fulfill, you will receive:
- 1 Silver
- 1 Small Healing Pill (Normal Quality)

For fulfilling all bonus tasks, you will receive:

- 5 Silver
- 1 Small Strengthening Pill (Normal Quality)
- 1 Tin Lottery Ticket (req. Nightmare Mode)

=== Growth of the family (1)

Grade: F

As a family man, how can your family be of a low rank? You should hurry up and increase the members of your family.

Task:

- Have 20 members in your family. Currently 7.

Reward:

- A free random building on your family homeland.

=== Power of believing (1)

Grade: E

Now that you have gained a core belief, you have to understand it's power, to really use it. For that, the first step is to grow it into a sapling, so you can use it.

Task:

- Grow your core belief seed into a sapling

Reward:

- A random core belief skill book.

=== Servant development (1) 

Grade: B

Each servant is a great asset for the master and has to be groomed carefully. Thus it is necessary to select the further development path for your servant. You can select one or more of the following paths:

- Warrior path

Your servant's development will focus on fighting.

War is everything and everything is war. (Dominus I)


- Management path

Your servant's development will focus on management. Because who doesn't need someone to manage one's assets?

Wealth is everything and there is nothing wealth can not buy. (Gregorius III)


- Relief path

Your servant's development will focus on serving you and supporting you. 

Relief is important because without stress everything will look better. And what could reduce one's stress more, than the service of a sexy servant? (Lucius VI)


Because o


